output_dir: "METAFORA_output"
scratch_dir: "./tmp"
sample_table: "example_input.sample_table.txt"
covariates: "example_input.covaraites.txt"

params:
  MAX_DEPTH: 30
  MIN_SEG_SIZE: 20
  MIN_ABS_ZSCORE: 3
  MIN_ABS_DELTA: 0.25
  SKIP_SEX_CHROMOSOME_ESTIMATION: FALSE
  
reference_fasta: /references/GRCH38/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta
reference_seqnames_table: ./GRCh38_ref_seqnames_table.txt

annotation_track_tsv: "metafora_grch38_report_annotations.tsv"
chrX_inactivation_regions: "references/X_inactivation_regions.GRCh38.bed"
