output_dir: "METAFORA_output"
scratch_dir: "./tmp"
sample_table: "example_input.sample_table.txt"
covariates: "example_input.covaraites.txt"

params:
  MAX_DEPTH: 30
  MIN_SEG_SIZE: 20
  MIN_ABS_ZSCORE: 3
  MIN_ABS_DELTA: 0.25
  SKIP_SEX_CHROMOSOME_ESTIMATION: FALSE
  
reference_fasta: /references/GRCH38/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta
reference_seqnames_table: ./GRCh38_ref_seqnames_table.txt

pb_cpg_tools: 
  bin: /tools/pb_tools/pb-CpG-tools-v2.3.2-x86_64-unknown-linux-gnu/bin/aligned_bam_to_cpg_scores
  model: /tools/pb_tools/pb-CpG-tools-v2.3.2-x86_64-unknown-linux-gnu/models/pileup_calling_model.v1.tflite

